coverage:
  status:
    project:
      default:
        threshold: 1%
        if_ci_failed: error
    patch:
      default:
        threshold: 1%
        if_ci_failed: error

test_analytics:
  # Enable test analytics features
  enabled: true
  
  # Notify on test failures
  notify:
    require_ci_to_pass: true

comment:
  layout: "diff, files"
  behavior: default
  require_changes: false